# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UrlRn.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bUrlRn.proto\x12\x05urlRn\"(\n\x13UrlByUsuarioRequest\x12\x11\n\tusuarioID\x18\x01 \x01(\x03\"5\n\x0f\x63rearUrlRequest\x12\x11\n\tusuarioID\x18\x01 \x01(\x03\x12\x0f\n\x07longUrl\x18\x02 \x01(\t\"=\n\x14UrlByUsuarioResponse\x12\x14\n\x0c\x63odRespuesta\x18\x01 \x01(\x05\x12\x0f\n\x07jsonUrl\x18\x02 \x01(\t2\x9d\x01\n\x05UrlRn\x12J\n\x0fgetUrlByUsuario\x12\x1a.urlRn.UrlByUsuarioRequest\x1a\x1b.urlRn.UrlByUsuarioResponse\x12H\n\x11\x63rearUrlByUsuario\x12\x16.urlRn.crearUrlRequest\x1a\x1b.urlRn.UrlByUsuarioResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UrlRn_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _URLBYUSUARIOREQUEST._serialized_start=22
  _URLBYUSUARIOREQUEST._serialized_end=62
  _CREARURLREQUEST._serialized_start=64
  _CREARURLREQUEST._serialized_end=117
  _URLBYUSUARIORESPONSE._serialized_start=119
  _URLBYUSUARIORESPONSE._serialized_end=180
  _URLRN._serialized_start=183
  _URLRN._serialized_end=340
# @@protoc_insertion_point(module_scope)
